server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://mysql-1.ciaw11pc2wlx.ap-northeast-2.rds.amazonaws.com/stat?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
  kafka:
    bootstrap-servers:
    - ec2-52-78-20-10.ap-northeast-2.compute.amazonaws.com:9092



